# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('advantages', models.TextField()),
                ('disadvantages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Background')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=64)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COG', models.IntegerField(default=0, verbose_name='Cognition')),
                ('COO', models.IntegerField(default=0, verbose_name='Coordination')),
                ('INT', models.IntegerField(default=0, verbose_name='Intuition')),
                ('REF', models.IntegerField(default=0, verbose_name='Reflexes')),
                ('SAV', models.IntegerField(default=0, verbose_name='Savvy')),
                ('SOM', models.IntegerField(default=0, verbose_name='Somatics')),
                ('WIL', models.IntegerField(default=0, verbose_name='Willpower')),
                ('MOXIE', models.IntegerField(default=0, verbose_name='Moxie')),
                ('INIT', models.IntegerField(default=0, verbose_name='Initiative')),
                ('LUC', models.IntegerField(default=0, verbose_name='Lucidity')),
                ('TT', models.IntegerField(default=0, verbose_name='Trauma Threshold')),
                ('IR', models.IntegerField(default=0, verbose_name='Insanity Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('advantages', models.TextField()),
                ('disadvantages', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Morph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MorphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('COG', models.IntegerField(default=0)),
                ('COO', models.IntegerField(default=0)),
                ('INT', models.IntegerField(default=0)),
                ('REF', models.IntegerField(default=0)),
                ('SAV', models.IntegerField(default=0)),
                ('SOM', models.IntegerField(default=0)),
                ('WIL', models.IntegerField(default=0)),
                ('DUR', models.IntegerField(default=0)),
                ('WT', models.IntegerField(default=0)),
                ('DR', models.IntegerField(default=0)),
                ('DB', models.IntegerField(default=0)),
                ('SPD', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PsiSleight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('linked', models.CharField(choices=[('MOXIE', 'Moxie'), ('COG', 'Cognition'), ('COO', 'Coordination'), ('INT', 'Intuition'), ('REF', 'Reflexes'), ('SAV', 'Savvy'), ('SOM', 'Somatics'), ('WIL', 'Willpower')], max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='morph',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.MorphModel'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='ego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Ego'),
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Faction'),
        ),
        migrations.AddField(
            model_name='character',
            name='morph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Morph'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(to='character.CharacterSkill'),
        ),
    ]
