# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20160810_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='skills',
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='character.Character'),
        ),
        migrations.AlterField(
            model_name='morph',
            name='effects',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
