# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_auto_20160810_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=256)),
                ('members', models.ManyToManyField(to='character.Character')),
            ],
        ),
        migrations.AlterField(
            model_name='background',
            name='advantages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='disadvantages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='characterskill',
            name='specialization',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='faction',
            name='advantages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='disadvantages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='morphmodel',
            name='advantages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='morphmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='morphmodel',
            name='disadvantages',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='morphmodel',
            name='implants',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='psisleight',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='linked',
            field=models.CharField(choices=[('COG', 'Cognition'), ('COO', 'Coordination'), ('INT', 'Intuition'), ('REF', 'Reflexes'), ('SAV', 'Savvy'), ('SOM', 'Somatics'), ('WIL', 'Willpower')], max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='parties',
            field=models.ManyToManyField(to='character.Party'),
        ),
    ]
